; Generated by tools/dis8085.js -- edit disasm/nt3321-22.json, not this file.
        CPU  8085
        PAGE 0

; ---- routines located in undumped ROM halves (see docs/rom-status.md) ----
HI_NIBBLE    EQU  0808H
FILL_ZERO    EQU  080FH
X_0817       EQU  0817H
SAVE_CUR_REC EQU  0875H
X_08A9       EQU  08A9H
X_0B8D       EQU  0B8DH
X_0D79       EQU  0D79H
X_0DB3       EQU  0DB3H
X_0DE3       EQU  0DE3H
X_0DE6       EQU  0DE6H
X_0E1A       EQU  0E1AH
X_0E1D       EQU  0E1DH
X_0E2D       EQU  0E2DH
X_0EC1       EQU  0EC1H
X_0ED9       EQU  0ED9H
X_0EEE       EQU  0EEEH
X_0F08       EQU  0F08H
X_0F23       EQU  0F23H
X_0F31       EQU  0F31H
X_0F6A       EQU  0F6AH
X_0FBE       EQU  0FBEH
X_0FE9       EQU  0FE9H
X_1804       EQU  1804H
X_1878       EQU  1878H
X_189B       EQU  189BH
X_18C0       EQU  18C0H
X_1940       EQU  1940H
X_1990       EQU  1990H
X_1995       EQU  1995H
X_199A       EQU  199AH
X_199F       EQU  199FH
X_19A4       EQU  19A4H
X_19A9       EQU  19A9H
X_19E7       EQU  19E7H
X_1DBD       EQU  1DBDH
X_1E05       EQU  1E05H
X_1E4C       EQU  1E4CH

; ---- external addresses (RAM / memory-mapped I/O) ----
EXTROM_SIG   EQU  2000H  ; rd=1 wr=0 lxi=0
EXTROM_ENTRY EQU  2001H  ; rd=0 wr=0 lxi=0
RAM1_BASE    EQU  6F00H  ; rd=0 wr=0 lxi=1
ACQ_COUNT    EQU  6F01H  ; rd=1 wr=0 lxi=1
FIRST_SLOT   EQU  6F02H  ; rd=0 wr=2 lxi=1
SLOT_RESULT  EQU  6F03H  ; rd=0 wr=2 lxi=0
SLOT_FLAGS   EQU  6F04H  ; rd=3 wr=1 lxi=3
WIN_END      EQU  6F0EH  ; rd=0 wr=4 lxi=4
TRACK_MASK   EQU  6F0FH  ; rd=1 wr=0 lxi=1
SLOT_IDX     EQU  6F11H  ; rd=8 wr=0 lxi=1
SLOT_IDX_B   EQU  6F12H  ; rd=1 wr=0 lxi=0
TRACK_STATE  EQU  6F13H  ; rd=0 wr=3 lxi=1
SLOT_COUNT   EQU  6F14H  ; rd=1 wr=1 lxi=3
SAMPLE_CNT   EQU  6F15H  ; rd=6 wr=3 lxi=2
SAMPLE_LO    EQU  6F16H  ; rd=1 wr=0 lxi=1
SYNC_FLAG    EQU  6F17H  ; rd=1 wr=1 lxi=0
GRI_TMP      EQU  6F18H  ; rd=0 wr=0 lxi=2
GRI_TMP_VAL  EQU  6F19H  ; rd=0 wr=1 lxi=0
GRI_BCD      EQU  6F1CH  ; rd=0 wr=0 lxi=4
GRI_VAL      EQU  6F1DH  ; rd=1 wr=1 lxi=0
GRI_BCD_HI   EQU  6F1FH  ; rd=0 wr=0 lxi=1
BCD_ACC      EQU  6F20H  ; rd=0 wr=0 lxi=5
BCD_ACC_HI   EQU  6F23H  ; rd=0 wr=0 lxi=1
REC_MASTER   EQU  6F24H  ; rd=0 wr=0 lxi=6
REC_MASTER_14 EQU  6F38H  ; rd=0 wr=0 lxi=1
REC_MASTER_16 EQU  6F3AH  ; rd=0 wr=1 lxi=0
REC_SEC      EQU  6F3DH  ; rd=0 wr=0 lxi=3
REC_SEC_TOA  EQU  6F41H  ; rd=0 wr=0 lxi=1
REC_SEC_14   EQU  6F51H  ; rd=0 wr=0 lxi=1
SETTLE_CNT   EQU  6F54H  ; rd=0 wr=1 lxi=1
CUR_REC      EQU  6FA1H  ; rd=2 wr=1 lxi=4
CUR_TOA      EQU  6FA5H  ; rd=0 wr=0 lxi=5
CUR_TOA_1    EQU  6FA6H  ; rd=1 wr=1 lxi=0
CUR_NPULSE   EQU  6FA9H  ; rd=4 wr=3 lxi=4
CUR_PULSES   EQU  6FAAH  ; rd=0 wr=0 lxi=3
CUR_PULSES_1 EQU  6FABH  ; rd=2 wr=2 lxi=0
CUR_PULSES_3 EQU  6FADH  ; rd=1 wr=2 lxi=0
CUR_PULSE_PTR EQU  6FAFH  ; rd=1 wr=2 lxi=0
CUR_MODE     EQU  6FB7H  ; rd=0 wr=2 lxi=0
CUR_FLAGS    EQU  6FBAH  ; rd=3 wr=2 lxi=1
PHASE_REF    EQU  6FBBH  ; rd=1 wr=0 lxi=1
PHASE_CODE   EQU  6FBFH  ; rd=2 wr=0 lxi=1
PHASE_CODE_HI EQU  6FC0H  ; rd=2 wr=0 lxi=0
DISP_MODE    EQU  6FC1H  ; rd=1 wr=0 lxi=0
BUTTONS      EQU  6FC4H  ; rd=3 wr=2 lxi=0
SEL_A        EQU  6FC5H  ; rd=3 wr=2 lxi=0
SEL_B        EQU  6FC6H  ; rd=3 wr=2 lxi=0
VAR_6FCB     EQU  6FCBH  ; rd=0 wr=1 lxi=0
GRI_SW       EQU  6FCCH  ; rd=1 wr=1 lxi=0
RESTART_REQ  EQU  6FCEH  ; rd=0 wr=1 lxi=0
BCD_DELTA    EQU  6FCFH  ; rd=0 wr=0 lxi=1
BCD_DELTA_2  EQU  6FD1H  ; rd=0 wr=0 lxi=2
BCD_DELTA_3  EQU  6FD2H  ; rd=0 wr=2 lxi=0
TOA_SAVE     EQU  6FD5H  ; rd=0 wr=0 lxi=2
VAR_6FD9     EQU  6FD9H  ; rd=0 wr=1 lxi=0
MISS_CNT     EQU  6FDAH  ; rd=0 wr=1 lxi=1
NEW_DATA     EQU  6FDCH  ; rd=0 wr=2 lxi=0
MISS_LIMIT   EQU  6FDDH  ; rd=1 wr=2 lxi=0
TOA_ALT      EQU  6FDEH  ; rd=0 wr=0 lxi=1
PULSE_BCD    EQU  6FDFH  ; rd=0 wr=1 lxi=0
VAR_6FE2     EQU  6FE2H  ; rd=1 wr=0 lxi=0
VAR_6FE3     EQU  6FE3H  ; rd=0 wr=0 lxi=1
VAR_6FE6     EQU  6FE6H  ; rd=0 wr=1 lxi=0
VAR_6FE7     EQU  6FE7H  ; rd=0 wr=2 lxi=0
BCD_TMP      EQU  6FE9H  ; rd=0 wr=0 lxi=5
M_6FEA       EQU  6FEAH  ; rd=0 wr=0 lxi=1
BCD_TMP_2    EQU  6FEBH  ; rd=0 wr=0 lxi=2
SLOTREC_CNT  EQU  6FEEH  ; rd=0 wr=0 lxi=1
SLOTREC_3    EQU  6FF1H  ; rd=0 wr=0 lxi=1
SLOTREC_5    EQU  6FF3H  ; rd=0 wr=0 lxi=1
RAM2_BASE    EQU  7000H  ; rd=0 wr=0 lxi=1
M_7034       EQU  7034H  ; rd=0 wr=0 lxi=1
M_7037       EQU  7037H  ; rd=0 wr=0 lxi=1
M_703A       EQU  703AH  ; rd=1 wr=0 lxi=0
KEY_CHANGED  EQU  703BH  ; rd=1 wr=2 lxi=0
BTN_STATE    EQU  703CH  ; rd=4 wr=3 lxi=0
TICK_BCD     EQU  703DH  ; rd=2 wr=1 lxi=0
PRTBUF       EQU  703EH  ; rd=0 wr=0 lxi=3
TX_PENDING   EQU  704EH  ; rd=2 wr=2 lxi=0
VAR_704F     EQU  704FH  ; rd=2 wr=1 lxi=0
VAR_7050     EQU  7050H  ; rd=0 wr=1 lxi=0
VAR_7051     EQU  7051H  ; rd=0 wr=1 lxi=0
SLOT_TBL     EQU  7054H  ; rd=0 wr=0 lxi=1
VAR_70BD     EQU  70BDH  ; rd=0 wr=1 lxi=0
VAR_70BE     EQU  70BEH  ; rd=0 wr=1 lxi=0
STATUS_BITS  EQU  70BFH  ; rd=2 wr=2 lxi=0
SW_D1        EQU  70C8H  ; rd=2 wr=1 lxi=0
SW_D2        EQU  70C9H  ; rd=2 wr=1 lxi=0
SW_D3        EQU  70CAH  ; rd=2 wr=1 lxi=0
SW_D4        EQU  70CBH  ; rd=2 wr=1 lxi=0
SW_HI        EQU  70CCH  ; rd=1 wr=1 lxi=0
SW_LO        EQU  70CDH  ; rd=2 wr=1 lxi=0
SW_LATCHED   EQU  70CEH  ; rd=1 wr=1 lxi=0
PLOT_COL     EQU  70CFH  ; rd=3 wr=1 lxi=1
RPT_STATE    EQU  70D0H  ; rd=6 wr=3 lxi=0
PRTBUF_PTR   EQU  70D1H  ; rd=1 wr=3 lxi=0
QUAL_LO      EQU  70D8H  ; rd=2 wr=1 lxi=0
TICK_HOOK    EQU  70DAH  ; rd=2 wr=0 lxi=0
OUT_MODE     EQU  70DCH  ; rd=2 wr=6 lxi=0
PROTO_STATE  EQU  70DDH  ; rd=5 wr=11 lxi=0
UNIT_ID      EQU  70DEH  ; rd=0 wr=2 lxi=2
OPTIONS      EQU  70DFH  ; rd=5 wr=6 lxi=0
RX_STATE     EQU  70E0H  ; rd=4 wr=9 lxi=0
RX_CHAR      EQU  70E1H  ; rd=7 wr=2 lxi=0
MON_PTR      EQU  70E2H  ; rd=4 wr=3 lxi=0
MON_PTR_HI   EQU  70E3H  ; rd=1 wr=0 lxi=0
MON_WORD     EQU  70E4H  ; rd=5 wr=2 lxi=0
MON_WORD_HI  EQU  70E5H  ; rd=0 wr=1 lxi=0
MON_DIGIT_FLAG EQU  70E6H  ; rd=1 wr=2 lxi=0
MON_LAST     EQU  70E7H  ; rd=1 wr=1 lxi=0
PLOT_BASE    EQU  70E8H  ; rd=1 wr=1 lxi=0
STACK_TOP    EQU  7100H  ; rd=0 wr=0 lxi=1
USART_DATA   EQU  0C000H  ; rd=1 wr=6 lxi=0
USART_CTRL   EQU  0C001H  ; rd=5 wr=2 lxi=0
KDC_DATA     EQU  0D000H  ; rd=14 wr=3 lxi=0
KDC_CMD      EQU  0D001H  ; rd=0 wr=10 lxi=0
PIO1_CMD     EQU  0E000H  ; rd=0 wr=1 lxi=0
PIO1_PC      EQU  0E003H  ; rd=7 wr=7 lxi=0
PIO1_TMRLO   EQU  0E004H  ; rd=0 wr=1 lxi=0
PIO1_TMRHI   EQU  0E005H  ; rd=0 wr=1 lxi=0
PIO2_CMD     EQU  0F000H  ; rd=0 wr=5 lxi=0
PIO2_PB      EQU  0F002H  ; rd=0 wr=1 lxi=1
PIO2_PC      EQU  0F003H  ; rd=3 wr=0 lxi=0
PIO2_TMRLO   EQU  0F004H  ; rd=0 wr=5 lxi=0
PIO2_TMRHI   EQU  0F005H  ; rd=0 wr=1 lxi=0


        ORG  0000H


; Reset vector. Interrupts off, jump to INIT.
RESET:
        DI
        JMP INIT

; Table of six 4-byte packed-BCD constants (little-endian, LS byte first).
; BCD_K_00080980 and BCD_K_00000110 are passed to X_0EC1 (missing half).
BCD_CONST_TBL:
        DB   08H,88H,88H,88H
        DB   00H,00H,02H,00H
        DB   00H,03H,00H,00H
        DB   06H,00H,00H,01H
BCD_K_00080980:
        DB   00H,08H,09H,80H
BCD_K_00000110:
        DB   00H,00H,01H,10H

; PULSE_PB2: pulse bit 2 of 8155#2 port B.
; PULSE_PB:  pulse the bits set in A on 8155#2 port B (XOR twice = toggle out and back).
; The 8155 output port latch is readable, so XRA M / MOV M,A works on the port.
PULSE_PB2:
        MVI A,04H
PULSE_PB:
        LXI H,PIO2_PB
        PUSH PSW
        XRA M
        MOV M,A
        POP PSW
        XRA M
        MOV M,A
        RET

; CPY_GRI_TO_TOA: copy the 4-byte GRI_BCD into CUR_TOA (HL=GRI_BCD, BC=CUR_TOA).
; CPY4_TO_TOA:    copy 4 bytes from (HL) into CUR_TOA.
CPY_GRI_TO_TOA:
        LXI H,GRI_BCD
CPY4_TO_TOA:
        LXI B,CUR_TOA
        JMP COPY4

; Three orphan bytes (never reached).
ORPHAN_0031:
        DB   30H,18H,3AH

; RST 6.5 interrupt: receiver sample-ready strobe.
; Entered only from the EI/NOP/DI window inside WAIT_SAMPLE, so the stack holds
; [ret into WAIT_SAMPLE][ret to WAIT_SAMPLE's caller]. The trailing POP B / RET discards
; the first and returns to the main-loop caller with A = B = PIO2_PC rotated left twice.
; Sets PIO1_PC bit 0 (busy) and acknowledges the receiver with a pulse on PIO2_PB bit 5.
RST65_ISR:
        DI
        LDA PIO1_PC
        ORI 01H
        STA PIO1_PC
        LDA PIO2_PC
        RLC
        RLC
        MOV B,A
        MVI A,20H                   ; ' '
        CALL PULSE_PB
        LDA CUR_REC
        RRC
        MOV A,B
        JC ISR_EXIT
        LDA SAMPLE_CNT
        INR A
        LXI H,WIN_END
        CMP M
        MOV A,B
        JNZ ISR_EXIT
        PUSH PSW
        PUSH D
        CALL PULSE_PB2
        CALL X_0E1D
        MVI A,20H                   ; ' '
        CALL PULSE_PB
        MVI A,01H
        STA SYNC_FLAG
        POP D
        POP PSW
ISR_EXIT:
        POP B
        RET

; INIT: cold start. Program the 8251 USART (mode 0DAH = async x16, 7 data, odd parity,
; 2 stop; command 37H = TxEN DTR RxE ER RTS), set SP, program both 8155s and the 8279,
; SIM 1DH = enable RST 6.5 only, clear RAM 6F00-70FB, read the front-panel switches,
; derive SLOT_COUNT from the GRI and fall into the acquisition sequence.
INIT:
        MVI A,0DAH
        STA USART_CTRL              ; 8251 mode: async x16, 7 data bits, odd parity, 2 stop bits
        LXI SP,STACK_TOP
        CALL PULSE_PB2
        MVI A,0CDH
        STA KDC_CMD                 ; 8279: clear display and FIFO (CD=110 CA=1)
        MVI A,0D0H
        STA PIO1_TMRLO              ; 8155#1 timer = 07D0H (2000), square wave
        MVI A,47H                   ; 'G'
        STA PIO1_TMRHI
        MVI A,0CFH
        STA PIO1_CMD                ; 8155#1: PA out, PB out, PC out, start timer
        MVI A,82H
        STA PIO2_TMRLO              ; 8155#2 timer = 0082H (130) -> 1200 baud x16
        MVI A,40H                   ; '@'
        STA PIO2_TMRHI
        MVI A,0C3H
        STA PIO2_CMD                ; 8155#2: PA out, PB out, PC input, start timer
        MVI A,8EH
        STA PIO2_PB                 ; 8155#2 port B idle pattern 8EH
        MVI A,37H                   ; '7'
        STA USART_CTRL              ; 8251 command: TxEN DTR RxE ER RTS
        MVI A,1DH
        SIM                         ; SIM 1DH: mask 5.5 & 7.5, enable 6.5, reset 7.5 latch
        MVI A,04H
        STA KDC_CMD                 ; 8279 mode: 8x8 display, encoded scan sensor matrix
        MVI A,26H                   ; '&'
        STA KDC_CMD                 ; 8279 clock prescaler = 6
        MVI A,90H
        STA KDC_CMD                 ; 8279: write display RAM, auto-increment, addr 0
        CALL X_1E4C
        MVI A,20H                   ; ' '
        CALL PULSE_PB
        MVI B,00H
        LXI H,RAM1_BASE
        CALL FILL_ZERO              ; clear 6F00-6FFF
        MVI B,0FCH
        LXI H,RAM2_BASE
        CALL FILL_ZERO              ; clear 7000-70FB (keeps return address at 70FE)
        MVI A,1BH
        STA VAR_6FD9
        MVI A,30H                   ; '0'
        STA UNIT_ID
        LXI H,PRTBUF
        SHLD PRTBUF_PTR
        MVI A,0FFH
        STA VAR_6FCB
        CALL READ_SWITCHES          ; read thumbwheels: SEL_A, SEL_B, GRI
        LHLD GRI_SW
        SHLD GRI_VAL
        LXI H,GRI_BCD
        CALL TOA_TO_BIN
        SUI 28H                     ; A = GRI-derived value - 40
        MVI E,04H
INIT_DIV10:
        INR E
        SUI 0AH
        JP INIT_DIV10
        MOV A,E
        STA SLOT_COUNT              ; SLOT_COUNT = 4 + (A-40)/10 + 1
        MOV B,A
        LXI H,FIRST_SLOT
        MVI M,01H
        XCHG
        LHLD SEL_A
        MOV A,L                     ; L = SEL_A, H = SEL_B
        CMP B
        JP INIT_CHK_SELB
        STA FIRST_SLOT
        PUSH B
        PUSH H
        CALL X_1DBD
        POP H
        POP B
INIT_CHK_SELB:
        LDA SEL_B
        CMP B
        JP ACQ_START
        CMP L
        JZ ACQ_START
        CALL X_1DBD

; ACQ_START: (re)start master acquisition. Reached again whenever tracking is lost.
ACQ_START:
        CALL CPY_GRI_TO_TOA
        LXI H,CUR_TOA
        CALL TOA_TO_BIN
        SUI 05H
        STA WIN_END
        MVI A,0EH
        CALL X_0DB3
        LXI H,CUR_REC
        LXI B,REC_MASTER
        CALL COPY4
        LXI H,BCD_K_00080980
        CALL X_0EC1
        MVI A,0EH
        CALL X_0DB3
        LXI H,CUR_REC
        LXI B,REC_SEC
        CALL COPY4
SEARCH_RESTART:
        CALL RESET_PULSES
        LXI B,REC_MASTER

; SEARCH_LOOP: search for the master phase code, alternating REC_MASTER / REC_SEC targets.
SEARCH_LOOP:
        CALL X_0DE6
        CALL WAIT_EPOCH
        CALL WAIT_SAMPLE
        XRA A
        STA SAMPLE_CNT
        CALL X_0ED9
        CALL FIRST_SAMPLE
        STC
        CALL MATCH_PULSES
        JNC SEARCH_VERIFY
        LDA CUR_NPULSE
        CPI 00H
        LXI B,REC_MASTER
        JNZ SEARCH_NEXT
        LXI B,REC_SEC
SEARCH_NEXT:
        JMP SEARCH_LOOP
SEARCH_VERIFY:
        CALL SAMPLE_TO_BCD
        CALL CPY_GRI_TO_TOA
        LXI H,BCD_DELTA_2
        CALL X_0EC1
        MVI A,0FH
        CALL X_0D79
        CALL WAIT_EPOCH
        CALL WAIT_SAMPLE
        CALL SHIFT_IN16
        XRI 0CAH                    ; compare shift-in byte with master phase code A (CA)
        JZ MASTER_FOUND
        JMP SEARCH_RESTART

; MASTER_FOUND: master locked. Slot 0 flags = C8H, then 20 settle passes (SETTLE_CNT).
MASTER_FOUND:
        MVI A,0C8H                  ; slot 0 flags = C8H
        STA SLOT_FLAGS
        CALL CLEAR_PULSES
        MVI A,01H
        STA CUR_MODE
        LXI H,0403H                 ; VAR_6FE7 = 03, VAR_6FE7+1 = 04
        SHLD VAR_6FE7
        MVI A,04H
        STA VAR_6FE6
        MVI A,14H                   ; 20 settle passes
        STA SETTLE_CNT
        LHLD GRI_VAL
        SHLD GRI_TMP_VAL
        CALL CPY_GRI_TO_TOA
        MVI A,0FH
        CALL X_0DB3
        LXI B,REC_MASTER
        CALL LOAD_REC_HL

; SETTLE_LOOP: 20 iterations accumulating signal quality (QUAL_LO/QUAL_HI).
SETTLE_LOOP:
        CALL X_0DE3
        CALL WAIT_EPOCH
        CALL X_0817
        CALL QUAL_UPDATE
        CALL X_0ED9
        LXI H,SETTLE_CNT
        DCR M
        JNZ SETTLE_LOOP
        LDA SLOT_FLAGS
        ANI 20H                     ; ' '
        JZ ACQ_START
        CALL QUAL_CHECK
        JC ACQ_START
        MVI A,03H
        STA REC_MASTER_16
        MVI A,10H
        STA VAR_6FE7
        CALL X_1E05
        CALL X_0F23
        LXI B,REC_MASTER
        CALL X_0DE6

; TRACK_LOOP: steady-state tracking loop, one pass per GRI epoch.
TRACK_LOOP:
        CALL WAIT_EPOCH
        CALL X_0EEE
        CALL X_0ED9
        LDA DISP_MODE
        CPI 01H
        JZ TRACK_DISP1
        CPI 02H
        JNZ TRACK_UPDATE
        CALL X_0F08
        JMP TRACK_UPDATE
TRACK_DISP1:
        CALL X_0F31
TRACK_UPDATE:
        CALL X_0817

; TRACK_NEXT_SLOT: advance SLOT_IDX (wraps at SLOT_COUNT); skip slots without bit 7.
TRACK_NEXT_SLOT:
        LXI H,SLOT_IDX
        INR M
        LDA SLOT_COUNT
        CMP M
        JNZ TRACK_SLOT_CHK
        MVI M,00H
        JMP TRACK_LOOP
TRACK_SLOT_CHK:
        CALL GET_SLOT_FLAGS
        MOV B,A
        RLC
        JC TRACK_SLOT_BIT6
        JMP TRACK_NEXT_SLOT
TRACK_SLOT_BIT6:
        RLC
        JNC SLOT_PROCESS
        CALL X_08A9
        JMP TRACK_NEXT_SLOT

; SLOT_PROCESS: load slot record into CUR_REC and dispatch on TRACK_STATE:
;   bit7 -> SLOT_TRACKING, bit6 -> SLOT_ACQUIRE, else initial window search.
SLOT_PROCESS:
        CALL LOAD_CUR_REC
        LXI H,TRACK_STATE
        MOV A,M
        RLC
        JC SLOT_TRACKING
        RLC
        JC SLOT_ACQUIRE
        MVI M,01H
        LDA ACQ_COUNT
        CPI 00H
        CZ X_0E1A
        MVI A,64H                   ; 'd'
        STA MISS_LIMIT
        LDA SLOT_IDX
        PUSH PSW
        MOV D,A
        MVI C,0AH
        CALL MUL8                   ; BC = SLOT_IDX * 10
        MVI A,10H
        ADD C
        STA WIN_END
        MOV A,C
        STA CUR_NPULSE
        POP PSW
        PUSH PSW
        DCR A
        JZ SLOT_CHK_NEXT
        CALL GET_FLAGS_A
        RLC
        JNC SLOT_CHK_NEXT
        RAR
        CALL SEC_TOA_TO_BIN
        ADI 0AH
        STA CUR_NPULSE
SLOT_CHK_NEXT:
        POP PSW
        INR A
        LXI H,SLOT_COUNT
        CMP M
        JNZ SLOT_CHK_NEXT2
        JMP TRACK_NEXT_SLOT
SLOT_USE_GRI:
        LXI H,GRI_BCD
        CALL TOA_TO_BIN
        SUI 04H
        STA WIN_END
        MVI A,82H
        STA MISS_LIMIT
        JMP SLOT_WIN_CALC
SLOT_CHK_NEXT2:
        INR A
        CMP M
        JZ SLOT_USE_GRI
        DCR A
        CALL GET_FLAGS_A
        RLC
        JNC SLOT_WIN_CALC
        RAR
        CALL SEC_TOA_TO_BIN
        SUI 04H
        STA WIN_END
SLOT_WIN_CALC:
        LDA CUR_NPULSE
        MOV B,A
        LXI H,WIN_END
        SUB M
        CMA
        INR A
        INR A
        MOV M,A
        CPI 09H
        JM TRACK_NEXT_SLOT
        MOV A,B
        CALL BCD_INC_STORE
        STA PULSE_BCD
        CALL COUNT_TRACKED
        LXI H,CUR_FLAGS
        MOV A,M
        ORA B
        MOV M,A
        LXI H,BCD_DELTA_2
        CALL CPY4_TO_TOA
        XRA A
        STA MISS_CNT
        CALL RESET_PULSES
        MVI A,80H
        STA TRACK_STATE
SLOT_DONE_06:
        MVI A,06H
SLOT_DONE:
        STA CUR_REC
SLOT_SAVE_NEXT:
        CALL SAVE_CUR_REC
        JMP TRACK_NEXT_SLOT

; SLOT_TRACKING: state 80H. Verify the pulse group; count misses (MISS_CNT / MISS_LIMIT).
SLOT_TRACKING:
        CALL WAIT_SAMPLE
        CALL X_0E2D
        CALL FIRST_SAMPLE
        STC
        CMC
        CALL MATCH_PULSES
        PUSH PSW
        LDA SYNC_FLAG
        RRC
        JC SLOT_TRK_RESULT
        CALL PULSE_PB2
        CALL X_0E1D
        MVI A,20H                   ; ' '
        CALL PULSE_PB
SLOT_TRK_RESULT:
        POP PSW
        JNC SLOT_TRK_LOST
        LDA CUR_NPULSE
        CPI 00H
        JNZ SLOT_TRK_END
SLOT_TRK_MISS:
        LXI H,BCD_K_00000110
        CALL X_0EC1
        LXI H,MISS_CNT
        INR M
        LDA MISS_LIMIT
        CMP M
        JNZ SLOT_TRK_END
        XRA A
        MOV M,A
        LXI H,TOA_ALT
        CALL CPY4_TO_TOA
SLOT_TRK_END:
        JMP SLOT_DONE_06
SLOT_TRK_LOST:
        MVI A,40H                   ; '@'
        STA TRACK_STATE
        CALL CLEAR_PULSES
        LXI B,TOA_SAVE
        LXI H,CUR_TOA
        CALL COPY4
        LDA CUR_TOA_1
        CALL BCD_TO_BIN
        SUI 09H
        LXI H,SAMPLE_CNT
        ADD M
        CALL BIN_TO_BCD
        STA CUR_TOA_1
SLOT_MODE3:
        MVI A,03H
        STA CUR_MODE
        MVI A,07H
        JMP SLOT_DONE

; SLOT_ACQUIRE: state 40H. Read the phase code, accumulate pulse counts, decide lock (state 80H).
SLOT_ACQUIRE:
        XRA A
        STA SAMPLE_CNT
        CALL WAIT_SAMPLE
        CALL X_0E1A
        CALL READ_PHASE
        LDA PHASE_CODE
        LXI H,CUR_NPULSE
        CALL COUNT_BITS4
        PUSH PSW
        MOV A,B
        ADD M
        MOV M,A
        POP PSW
        INX H
        CALL COUNT_BITS4
        MOV A,B
        ADD M
        MOV M,A
        INX H
        INR M
        MOV A,M
        CPI 04H
        JNZ SLOT_ACQ_CHK8
        CALL CHK_NPULSE
        JC SLOT_ACQ_FAIL
        JMP SLOT_SAVE_NEXT
SLOT_ACQ_CHK8:
        CPI 08H
        JNZ SLOT_SAVE_NEXT
        CALL CHK_NPULSE
        JNC SLOT_ACQ_OK
SLOT_ACQ_FAIL:
        MVI A,80H
        STA TRACK_STATE
        CALL RESET_PULSES
        LXI H,TOA_SAVE
        CALL CPY4_TO_TOA
        JMP SLOT_TRK_MISS
SLOT_ACQ_OK:
        CALL X_1E05
        STA SLOT_RESULT
        LXI H,ACQ_COUNT
        INR M
        MOV A,M
        CPI 01H
        JNZ SLOT_ACQ_FLAGS
        LDA SLOT_IDX
        STA FIRST_SLOT
SLOT_ACQ_FLAGS:
        LDA CUR_FLAGS
        PUSH PSW
        CALL BIT_OF_STA
        ORA M
        MOV M,A
        POP PSW
        ORI 0C0H
        STA CUR_FLAGS
        MVI A,01H
        STA NEW_DATA
        CALL CLEAR_PULSES
        JMP SLOT_MODE3

; QUAL_UPDATE: count zero bits in each nibble of PHASE_CODE into QUAL_LO/QUAL_HI (saturate at 40H).
QUAL_UPDATE:
        LDA PHASE_CODE
        CMA
        LHLD QUAL_LO
        MVI E,04H
QUAL_LO_LOOP:
        RRC
        JNC QUAL_LO_NEXT
        INR L
QUAL_LO_NEXT:
        DCR E
        JNZ QUAL_LO_LOOP
        PUSH PSW
        MOV A,L
        CPI 40H                     ; '@'
        JC QUAL_HI_START
        MVI L,40H                   ; '@'
QUAL_HI_START:
        POP PSW
        MVI E,04H
QUAL_HI_LOOP:
        RRC
        JNC QUAL_HI_NEXT
        INR H
QUAL_HI_NEXT:
        DCR E
        JNZ QUAL_HI_LOOP
        MOV A,H
        CPI 40H                     ; '@'
        JC QUAL_STORE
        MVI H,40H                   ; '@'
QUAL_STORE:
        SHLD QUAL_LO
        RET

; QUAL_CHECK: carry set if either QUAL counter < 28H (poor signal).
QUAL_CHECK:
        LHLD QUAL_LO
        MOV A,L
        CPI 28H                     ; '('
        JC QUAL_BAD
        MOV A,H
        CPI 28H                     ; '('
        JC QUAL_BAD
        STC
        CMC
        RET
QUAL_BAD:
        STC
        RET

; WAIT_SAMPLE: idle/background loop. Opens a one-instruction interrupt window (EI NOP DI);
; when RST 6.5 fires the ISR returns directly to WAIT_SAMPLE's caller (see RST65_ISR).
; Between windows: optional expansion ROM hook at 2000H (signature 0A5H), serial receive,
; serial transmit, and, if RST 7.5 latched (RIM bit 6), the periodic tick tasks.
WAIT_SAMPLE:
        EI                          ; one-instruction window for RST 6.5
        NOP
        DI
        PUSH PSW
        PUSH D
        LDA EXTROM_SIG              ; expansion ROM present if 2000H = 0A5H
        CPI 0A5H
        CZ EXTROM_ENTRY
        CALL SERIAL_POLL
        CALL TX_SERVICE
        RIM
        ANI 40H                     ; RIM bit 6 = RST 7.5 pending
        JZ WAIT_SAMPLE_END
        LDA PIO1_PC
        ORI 01H                     ; PIO1 PC0 = busy
        STA PIO1_PC
        MVI A,10H
        SIM                         ; SIM 10H: reset RST 7.5 latch
        LDA TICK_HOOK
        CPI 00H
        CNZ CALL_TICK_HOOK
        CALL REPORT_TASK
        CALL X_18C0
        CALL TICK_TASK
WAIT_SAMPLE_END:
        POP D
        POP PSW
        LDA PIO1_PC
        ANI 0FEH                    ; PIO1 PC0 = idle
        STA PIO1_PC
        JMP WAIT_SAMPLE

; WAIT_EPOCH: wait for a sample whose status (PIO2_PC bit 2, seen as bit 4 after RLC RLC) is set.
WAIT_EPOCH:
        CALL WAIT_SAMPLE
        MOV B,A
        ANI 10H                     ; bit 4 = PIO2_PC bit 2 (epoch flag)
        MOV A,B
        JZ WAIT_EPOCH
        LDA PIO1_PC
        ORI 01H
        STA PIO1_PC
        RET

; SHIFT_IN16: clock 8 bits out of the receiver shift register via PIO2_PB bit 4.
; PIO2_PC bit 4 -> B (phase-code stream), bit 3 -> C (second stream). Returns A = B.
SHIFT_IN16:
        MVI D,08H
        LDA PIO2_PC
        JMP SHIFT_IN_BIT
SHIFT_IN_CLK:
        MVI A,10H                   ; clock pulse on PIO2_PB bit 4
        CALL PULSE_PB
        LDA PIO2_PC
SHIFT_IN_BIT:
        RLC
        RLC
        RLC
        RLC
        PUSH PSW
        MOV A,B
        RAL
        MOV B,A
        POP PSW
        RLC
        MOV A,C
        RAL
        MOV C,A
        DCR D
        JNZ SHIFT_IN_CLK
        MOV A,B
        RET

; READ_PHASE: SHIFT_IN16 then XOR with PHASE_REF -> PHASE_CODE (2 bytes).
READ_PHASE:
        CALL SHIFT_IN16
        LXI H,PHASE_REF
        LXI D,PHASE_CODE
        XRA M
        STAX D
        MOV A,C
        XRA M
        INX D
        STAX D
        RET

; GET_SLOT_FLAGS: A = SLOT_FLAGS[SLOT_IDX].  GET_FLAGS_A: A = SLOT_FLAGS[A].
GET_SLOT_FLAGS:
        LDA SLOT_IDX
GET_FLAGS_A:
        LXI H,SLOT_FLAGS
        ADD L
        MOV L,A
        MOV A,M
        RET

; GET_SLOT_REC: HL -> 25-byte station record for SLOT_IDX.
; Slot 0 = REC_MASTER; otherwise REC_SEC + 25 * (flags & 3).
GET_SLOT_REC:
        LDA SLOT_IDX
        LXI H,REC_MASTER
        CPI 00H
        RZ
        CALL GET_FLAGS_A
        LXI H,REC_SEC
        JMP REC_INDEX

; GET_SEC_TOA: HL -> REC_SEC_TOA + 25 * (A & 3).
GET_SEC_TOA:
        LXI H,REC_SEC_TOA
REC_INDEX:
        ANI 03H
        LXI D,0019H                 ; record stride 25
REC_INDEX_LOOP:
        DCR A
        RM
        DAD D
        JMP REC_INDEX_LOOP

; MUL9_INDEX: A = (HL + 9*A). Patched: the original x10 body survives at OLD_MUL10.
MUL9_INDEX:
        PUSH B
        MOV B,A
        RLC
        ADD B
        MOV B,A
        RLC
        ADD B
        JMP MUL9_INDEX_2

; OLD_MUL10: dead code left by an in-place patch (PUSH B / RLC / MOV C,A / RLC / RLC / ADD C).
OLD_MUL10:
        DB   0C5H,07H,4FH,07H,07H,81H
MUL9_INDEX_2:
        MOV C,A
        MVI B,00H
        DAD B
        MOV A,M
        POP B
        RET

; LOAD_CUR_REC: CUR_FLAGS = slot flags; copy the slot's 25-byte record into CUR_REC.
LOAD_CUR_REC:
        CALL GET_SLOT_FLAGS
        STA CUR_FLAGS
        CALL GET_SLOT_REC
        LXI B,CUR_REC
COPY25_TO_CUR:
        MVI E,19H
        JMP COPY_E                  ; copy 25 bytes

; OLD_LOAD_REC: dead code left by an in-place patch (copied in the opposite direction).
OLD_LOAD_REC:
        DB   0CDH,0E1H,04H,3AH,0BAH,6FH
        DB   77H,0CDH,0EBH,04H,44H,4DH
LOAD_REC_HL:
        LXI H,CUR_REC
        JMP COPY25_TO_CUR

; BIT_OF_STA: A = 1 << (A & 3), HL = TRACK_MASK.
BIT_OF_STA:
        LXI H,TRACK_MASK
        ANI 03H
        MOV B,A
        MVI A,01H
BIT_OF_LOOP:
        DCR B
        RM
        RLC
        JMP BIT_OF_LOOP

; COUNT_TRACKED: B = number of set bits in TRACK_MASK.
COUNT_TRACKED:
        MVI B,00H
        LDA TRACK_MASK
COUNT_TRK_LOOP:
        RRC
        RNC
        INR B
        JMP COUNT_TRK_LOOP

; SEC_TOA_TO_BIN / TOA_TO_BIN: A = bin(HL[1]) + (HL[2] >= 60H BCD ? 1 : 0).
SEC_TOA_TO_BIN:
        CALL GET_SEC_TOA
TOA_TO_BIN:
        MVI B,00H
        INX H
        INX H
        MOV A,M
        RAR
        SUI 30H                     ; '0'
        JM TOA_TO_BIN_2
        INR B
TOA_TO_BIN_2:
        DCX H
        MOV A,M
        PUSH B
        CALL BCD_TO_BIN
        POP B
        ADD B
        RET
BCD_INC_STORE:
        INR A
        JMP BIN_TO_DELTA

; RESET_PULSES: clear pulse list and reset CUR_PULSE_PTR to CUR_PULSES.
RESET_PULSES:
        CALL CLEAR_PULSES
        LXI H,CUR_PULSES
        SHLD CUR_PULSE_PTR
        RET

; CLEAR_PULSES: zero 17 bytes from CUR_NPULSE (falls into FILL_ZERO in the missing half).
CLEAR_PULSES:
        MVI B,11H
        LXI H,CUR_NPULSE
        JMP FILL_ZERO

; ORPHAN_058C: dead code from a patch, followed by the Loran-C phase-code table
; (CA F9 = master A / secondary A, 9F AC = master B / secondary B, each preceded by 21H LXI-skip).
ORPHAN_058C:
        DB   21H,04H,6FH,7EH,07H,3FH,1FH,77H
PHASE_CODE_TBL:
        DB   07H,21H,0CAH
        DB   0F9H,0D8H,21H
        DB   9FH,0ACH,0C9H

; PHASE_MISMATCH: B = popcount(PHASE_REF XOR B) = number of phase-code bit errors.
PHASE_MISMATCH:
        LDA PHASE_REF
        XRA B
        MVI C,08H
        MVI B,00H
PM_LOOP:
        RLC
        JNC PM_NEXT
        INR B
PM_NEXT:
        DCR C
        JNZ PM_LOOP
        RET

; FIRST_SAMPLE: wait one sample, SAMPLE_CNT = 8, read shift register, SAMPLE_LO = C.
FIRST_SAMPLE:
        CALL WAIT_SAMPLE
        MVI A,08H
        STA SAMPLE_CNT
        CALL SHIFT_IN16
        LXI H,SAMPLE_LO
        MOV M,C
        INX H
        MVI M,00H
        RET

; MATCH_PULSES: walk samples until WIN_END, matching the master phase code
; (0CAH on 'A' GRIs, 09FH on 'B' GRIs) and building the pulse-position list.
; Entry carry flag selects exact compare (CY=1) or 1-bit-tolerant compare (CY=0).
MATCH_PULSES:
        PUSH PSW
        LDA SAMPLE_LO
        LXI H,CUR_NPULSE
        MOV E,M
        JMP MP_TEST
MP_NEXT_SAMPLE:
        LXI H,SAMPLE_CNT
        INR M
        INX H
        RLC
        MOV A,M
        RAL
        MOV M,A
MP_TEST:
        MOV B,A
        MOV A,E
        CPI 00H
        JNZ MP_HAVE_PULSES
        POP PSW
        PUSH PSW
        JC MP_MASTER_A
        CALL PHASE_MISMATCH
        MOV A,B
        CPI 02H
        JC MP_ADD_PULSE
        JMP MP_CHK_END
MP_MASTER_A:
        MVI A,0CAH                  ; master phase code, GRI A
        XRA B
        JZ MP_ADD_PULSE
MP_CHK_END:
        LDA SAMPLE_CNT
        LXI H,WIN_END
        CMP M
        JZ MP_DONE_C
MP_WAIT:
        CALL WAIT_SAMPLE
        JMP MP_NEXT_SAMPLE
MP_DONE_C:
        POP PSW
        STC
        RET
MP_ADD_PULSE:
        LHLD CUR_PULSE_PTR
        LDA SAMPLE_CNT
        MOV M,A
        INX H
        SHLD CUR_PULSE_PTR
        LXI H,CUR_NPULSE
        INR M
        JMP MP_CHK_END
MP_HAVE_PULSES:
        POP PSW
        PUSH PSW
        JC MP_MASTER_B
        CALL PHASE_MISMATCH
        JMP MP_FIND
MP_MASTER_B:
        MVI A,9FH                   ; master phase code, GRI B
        XRA B
        MOV B,A
MP_FIND:
        LDA SAMPLE_CNT
        MOV C,A
        LXI H,CUR_PULSES
        MVI D,05H
MP_FIND_LOOP:
        MOV A,C
        CMP M
        JZ MP_FOUND
        INX H
        DCR D
        JNZ MP_FIND_LOOP
        JMP MP_CHK_END2
MP_FOUND:
        MOV A,B
        CPI 00H
        JZ MP_DONE_NC
        POP PSW
        PUSH PSW
        JC MP_CHK_END2
        MOV A,B
        CPI 02H
        JC MP_DONE_NC
MP_CHK_END2:
        LDA SAMPLE_CNT
        LXI H,WIN_END
        CMP M
        JZ MP_WINDOW_END
        JMP MP_WAIT
MP_WINDOW_END:
        CALL RESET_PULSES
        JMP MP_DONE_C
MP_DONE_NC:
        POP PSW
        XRA A
        RET

; SAMPLE_TO_BCD: BCD_DELTA_3 = BCD(SAMPLE_CNT - 9).  BIN_TO_DELTA: BCD_DELTA_3 = BCD(A).
SAMPLE_TO_BCD:
        LDA SAMPLE_CNT
        SUI 09H
BIN_TO_DELTA:
        CALL BIN_TO_BCD
        STA BCD_DELTA_3
        RET

; COUNT_BITS4: B = popcount of low 4 bits of A.
COUNT_BITS4:
        MVI C,04H
        MVI B,00H
CB4_LOOP:
        RRC
        JNC CB4_NEXT
        INR B
CB4_NEXT:
        DCR C
        JNZ CB4_LOOP
        RET

; CHK_NPULSE: carry if CUR_NPULSE bytes >= 6, else zero them.
CHK_NPULSE:
        LHLD CUR_NPULSE
        MOV A,L
        SUI 06H
        JP CHK_NPULSE_OK
        MOV A,H
        SUI 06H
        JP CHK_NPULSE_OK
        LXI H,RESET
        XRA A
        SHLD CUR_NPULSE
        RET
CHK_NPULSE_OK:
        STC
        RET

; ADJ_PULSES: pulse-position adjustment; computes a signed 16-bit offset (NEG_HL for
; negative) and adds/subtracts BCD_DELTA into BCD_ACC with BCD_ADD4 / BCD_SUB4.
ADJ_PULSES:
        LHLD CUR_PULSES_1
        LDA CUR_REC
        ANI 02H
        JZ ADJ_OFFSET
        LXI D,CUR_PULSES
        LDAX D
        MOV B,A
        RLC
        MOV A,B
        JNC ADJ_SUB16
        ADI 10H
        STAX D
        DCX H
        JMP ADJ_STORE
ADJ_SUB16:
        SUI 10H
        JM ADJ_OFFSET
        STAX D
        INX H
ADJ_STORE:
        SHLD CUR_PULSES_1
ADJ_OFFSET:
        XCHG
        LHLD CUR_PULSES_3
        DAD D
        MOV A,H
        RLC
        MVI E,00H
        CC NEG_HL
        PUSH H
        PUSH D
        MVI D,04H
ADJ_SHL4:
        MOV A,L
        RLC
        MOV L,A
        MOV A,H
        RAL
        MOV H,A
        DCR D
        JNZ ADJ_SHL4
        ADD E
        RLC
        CALL BIN_TO_BCD
        STA BCD_DELTA_3
        CPI 00H
        JZ ADJ_ZERO
        POP D
        POP H
        MVI H,00H
        MOV A,L
        ANI 0FH
        MOV L,A
        MOV A,E
        RRC
        PUSH PSW
        JNC ADJ_APPLY
        LXI D,0FFF0H                ; DE = -16
        DAD D
        CALL NEG_HL
ADJ_APPLY:
        SHLD CUR_PULSES_3
        LXI H,BCD_DELTA
        LXI B,BCD_ACC
        POP PSW
        JNC BCD_ADD4
        JMP BCD_SUB4
ADJ_ZERO:
        POP D
        POP H
        SHLD CUR_PULSES_3
        LDA CUR_FLAGS
        ANI 08H
        RZ
        LDA VAR_6FE2
        RRC
        RRC
        RNC
        LXI H,BCD_ACC_HI
        MVI M,02H
        RET

; NEG_HL: HL = -HL, E = E + 1 (sign flag).
NEG_HL:
        MOV A,H
        CMA
        MOV H,A
        MOV A,L
        CMA
        MOV L,A
        INX H
        INR E
        RET

; CALC_TD: form the time difference: copy TOA (or GRI) to BCD_ACC, adjust, store to CUR_TOA.
CALC_TD:
        LDA CUR_FLAGS
        ANI 08H
        JNZ CALC_TD_GRI
        LDA SLOT_IDX
        CPI 00H
        JZ CALC_TD_TMP
        LXI H,CUR_TOA
        LXI B,BCD_ACC
        CALL COPY4
        LHLD CUR_PULSES_1
        LXI B,0001H                 ; BC = 1
        CALL X_0B8D
        SHLD CUR_PULSES_1
        CALL ADJ_PULSES
        LXI H,BCD_ACC
        JMP CALC_TD_STORE
CALC_TD_GRI:
        LXI H,GRI_BCD
        LXI B,BCD_ACC
        CALL COPY4
        CALL ADJ_PULSES
        LXI H,BCD_ACC
        LXI B,GRI_TMP
        CALL COPY4
        LDA SLOT_IDX
        CPI 00H
        JNZ CALC_TD_EXIT
CALC_TD_TMP:
        LXI H,GRI_TMP
CALC_TD_STORE:
        LXI B,CUR_TOA
        CALL COPY4
CALC_TD_EXIT:
        LXI H,VAR_6FE3
        RET

; BCD_ADD4: (BC) += (HL), 4 packed-BCD bytes, LS byte first.
; PTR_TO_MSB: HL += DE-1, BC += DE-1 (point both at the MS byte).
BCD_ADD4:
        LXI D,0004H                 ; DE = 4 bytes
        CALL PTR_TO_MSB
        XRA A
BCD_ADD4_LOOP:
        LDAX B
        ADC M
        DAA
        STAX B
        DCR E
        RZ
        DCX B
        DCX H
        JMP BCD_ADD4_LOOP
PTR_TO_MSB:
        DAD D
        DCX H
        PUSH H
        MOV H,B
        MOV L,C
        DAD D
        DCX H
        MOV B,H
        MOV C,L
        POP H
        RET

; BCD_SUB4: (BC) -= (HL), 4 packed-BCD bytes, ten's-complement subtract.
BCD_SUB4:
        LXI D,0004H                 ; DE = 4 bytes
        CALL PTR_TO_MSB
        PUSH D
        PUSH B
        POP D
        POP B
        STC
BCD_SUB4_LOOP:
        MVI A,99H
        ACI 00H
        SUB M
        XCHG
        ADD M
        DAA
        MOV M,A
        XCHG
        DCR C
        RZ
        DCX D
        DCX H
        JMP BCD_SUB4_LOOP

; COPY4: copy 4 bytes (HL) -> (BC).  COPY_E: copy E bytes.
COPY4:
        MVI E,04H
COPY_E:
        MOV A,M
        STAX B
        INX H
        INX B
        DCR E
        JNZ COPY_E
        RET

; MUL8: BC = C * D (shift-add, 8x8 -> 16).
MUL8:
        MVI B,00H
        MVI E,09H
MUL8_LOOP:
        MOV A,C
        RAR
        MOV C,A
        DCR E
        RZ
        MOV A,B
        JNC MUL8_SHIFT
        ADD D
MUL8_SHIFT:
        RAR
        MOV B,A
        JMP MUL8_LOOP

; BCD_TO_BIN: A = binary value of packed-BCD byte A (uses HI_NIBBLE in the missing half).
BCD_TO_BIN:
        MOV B,A
        CALL HI_NIBBLE
        MOV E,A
        XRA A
        MVI D,0AH
B2B_LOOP:
        DCR E
        JM B2B_DONE
        ADD D
        JMP B2B_LOOP
B2B_DONE:
        MOV C,A
        MVI A,0FH
        ANA B
        ADD C
        RET

; BIN_TO_BCD: A = packed BCD of binary A (0..99). Continues at 0800 in the missing half:
; RLC RLC RLC / ADD H / RET.
BIN_TO_BCD:
        MVI E,00H
        MVI D,0AH
B2D_LOOP:
        SUB D
        JC B2D_DONE
        INR E
        JMP B2D_LOOP
B2D_DONE:
        ADD D
        MOV H,A
        XRA A
        MOV A,E
        RLC
; ---- 0800-0FFF: unprogrammed / not dumped (reads as 0FFH) ----

        ORG  1000H


; SLOTTBL_CHK: tail of a routine from the missing half (entered from 0FFxH):
; test SLOT_TBL[A]; clean up stack and continue at X_0FE9 or SLOT_INC_CHK.
SLOTTBL_CHK:
        MOV C,A
        MVI B,00H
        LXI H,SLOT_TBL
        DAD B
        MOV A,M
        CPI 00H
        POP B
        POP H
        JZ SLOTTBL_ZERO
        POP PSW
        JMP X_0FE9
SLOTTBL_ZERO:
        POP PSW
        MOV A,B
        JMP SLOT_INC_CHK
        DB   0F1H
SLOT_INC_CHK:
        INR A
        LXI H,SLOT_COUNT
        CMP M
        JNZ X_0FBE
        RET
CHK_H_NEG:
        MOV A,H
        RLC
        JC X_0F6A
        RET

; SLOTREC_PHASE: update the 9-byte per-slot record from PHASE_CODE_HI.
SLOTREC_PHASE:
        LDA SLOT_IDX
        LXI H,SLOTREC_5
        CALL MUL9_INDEX
        MOV C,M
        LDA PHASE_CODE_HI
        XRI 3FH                     ; '?'
        DCR C
        DCR C
        DCR C
        MVI E,03H
SRP_LOOP:
        RLC
        JNC SRP_NEXT
        INR C
        INR C
SRP_NEXT:
        DCR E
        JNZ SRP_LOOP
        MOV A,C
        ADI 08H
        RLC
        MVI A,00H
        RAR
        INX H
        MOV M,A
        DCX H
        MOV A,C
        RLC
        JNC SRP_STORE
        MOV A,C
        ADI 10H
        RLC
        RNC
SRP_STORE:
        MOV M,C
        RET

; SLOTREC_UPDATE: bump the per-slot counter, subtract BCD_TMP / 0400H, add popcount, etc.
SLOTREC_UPDATE:
        LDA SLOT_IDX
        LXI H,SLOTREC_CNT
        CALL MUL9_INDEX
        INX H
        PUSH H
        DCX H
        INR M
        MOV A,M
        CPI 02H
        JZ SRU_SUB
        CPI 05H
        JNZ SRU_SUB4
        MVI M,00H
SRU_SUB:
        POP H
        PUSH H
        LXI B,M_6FEA
        CALL COPY4
        LXI H,BCD_TMP
        MVI M,00H
        POP B
        PUSH B
        LXI H,BCD_TMP
        CALL BCD_SUB4
SRU_SUB4:
        LXI B,0400H                 ; B = 4 bytes (C ignored)
        LXI H,BCD_TMP
        CALL FILL_ZERO
        LXI H,BCD_TMP_2
        MVI M,04H
        POP B
        PUSH B
        LXI H,BCD_TMP
        CALL BCD_SUB4
        LXI H,BCD_TMP_2
        MVI M,00H
        LDA PHASE_CODE_HI
        CMA
        MVI E,08H
SRU_CNT_LOOP:
        RRC
        JNC SRU_CNT_NEXT
        INR M
SRU_CNT_NEXT:
        DCR E
        JNZ SRU_CNT_LOOP
        POP B
        PUSH B
        LXI H,BCD_TMP
        CALL BCD_ADD4
        POP B
        LDAX B
        CPI 00H
        JZ SRU_ZERO
        MOV H,B
        MOV L,C
        PUSH B
        MVI B,04H
        CALL FILL_ZERO
        POP B
        RET
SRU_ZERO:
        INX B
        LDAX B
        ANI 0F0H
        RZ
        MVI A,10H
        STAX B
        INX B
        MVI A,00H
        STAX B
        RET

; CALL_TICK_HOOK: jump through TICK_HOOK (set by the missing half or the monitor).
CALL_TICK_HOOK:
        LHLD TICK_HOOK
        PCHL

; SERIAL_POLL: 8251 receive state machine (RX_STATE / PROTO_STATE). See docs/serial-protocol.md.
; Also runs PLOT_OUT when OUT_MODE = 2.
SERIAL_POLL:
        LDA OUT_MODE
        CPI 02H
        CZ PLOT_OUT
        LDA RX_STATE
        CPI 00H
        JNZ RX_STATE_N
        LDA USART_CTRL
        RAR                         ; RxRDY?
        RAR
        RNC
        LDA USART_DATA
        STA RX_CHAR
        LDA RX_STATE
        INR A
        STA RX_STATE
        JMP SERIAL_POLL
RX_STATE_N:
        LDA USART_CTRL
        RAR                         ; TxRDY?
        RNC
        LDA PIO1_PC
        ORI 01H
        STA PIO1_PC
        LDA RX_STATE
        INR A
        STA RX_STATE
        CPI 02H
        JNZ TX_STATE_N
        LDA RX_CHAR
        CPI 12H                     ; DC2: reset protocol
        JNZ RX_CMD_14
        MVI A,00H
        STA PROTO_STATE
        STA OUT_MODE
        JMP RX_DONE
RX_CMD_14:
        CPI 14H                     ; DC4: OUT_MODE = 1
        JNZ RX_CMD_07
        MVI A,01H
        STA OUT_MODE
        JMP RX_DONE
RX_CMD_07:
        CPI 07H                     ; BEL: reset print buffer, PROTO_STATE = 1
        JNZ RX_CMD_05
        LXI H,PRTBUF
        SHLD PRTBUF_PTR
        MVI A,00H
        STA OUT_MODE
        MVI A,01H
        STA PROTO_STATE
        JMP RX_DONE
RX_CMD_05:
        CPI 05H                     ; ENQ: PROTO_STATE = 2
        JNZ RX_PROTO_4
        MVI A,02H
        STA PROTO_STATE
        JMP RX_DONE
RX_PROTO_4:
        LDA PROTO_STATE
        CPI 04H
        JNZ RX_PROTO_5
        LDA RX_CHAR
        CPI 41H                     ; 'A'
        JNZ RX_PROTO_4B
        MVI A,05H
        STA PROTO_STATE
        JMP RX_DONE
RX_PROTO_4B:
        CPI 2CH                     ; ','
        JNZ RX_PROTO_RESET
        MVI A,06H
        STA PROTO_STATE
        JMP RX_DONE
RX_PROTO_RESET:
        MVI A,00H
        STA PROTO_STATE
        JMP RX_DONE
RX_PROTO_5:
        LDA PROTO_STATE
        CPI 05H
        JNZ RX_PROTO_6
        LDA RX_CHAR
        LXI H,UNIT_ID
        CMP M
        JNZ RX_PROTO_SET1
        MVI A,02H
        STA PROTO_STATE
        JMP RX_DONE
RX_PROTO_SET1:
        MVI A,01H
        STA PROTO_STATE
        JMP RX_DONE
RX_PROTO_6:
        LDA PROTO_STATE
        CPI 06H
        JNZ RX_CHK_ESC
        LDA RX_CHAR
        LXI H,UNIT_ID
        CMP M
        JNZ RX_PROTO_SET1
        MVI A,03H
        STA PROTO_STATE
        JMP RX_DONE
RX_CHK_ESC:
        LDA RX_CHAR
        CPI 1BH                     ; ESC: PROTO_STATE = 4
        JNZ RX_CHK_MON
        MVI A,04H
        STA PROTO_STATE
        JMP RX_DONE
RX_CHK_MON:
        LDA PROTO_STATE
        CPI 03H
        JZ MON_CMD
RX_DONE:
        MVI A,00H
        STA RX_STATE
        RET

; MON_CMD: memory monitor commands, active when PROTO_STATE = 3. Char is echoed first.
;   ' ' deposit MON_WORD low byte at (MON_PTR), advance   R back up one address
;   S set MON_PTR = MON_WORD   G call MON_WORD   M dump memory   K/P/O output mode 1/2/0
;   0-9 A-F shift hex digit into MON_WORD
MON_CMD:
        LDA RX_CHAR
        STA USART_DATA              ; echo command char
        CPI 20H                     ; ' '
        JNZ MON_CMD_R
        LDA MON_DIGIT_FLAG
        CPI 00H
        LHLD MON_PTR
        JZ MON_ADVANCE
        LDA MON_WORD
        MOV M,A
MON_ADVANCE:
        INX H
        SHLD MON_PTR
MON_CLR_DIGIT:
        MVI A,00H
        STA MON_DIGIT_FLAG
        JMP SERIAL_POLL
MON_CMD_R:
        CPI 52H                     ; 'R'
        JNZ MON_CMD_S
        LHLD MON_PTR
        DCX H
        SHLD MON_PTR
        JMP MON_CLR_DIGIT
MON_CMD_S:
        CPI 53H                     ; 'S'
        JNZ MON_CMD_G
        LHLD MON_WORD
        SHLD MON_PTR
        JMP MON_CLR_DIGIT
MON_CMD_G:
        CPI 47H                     ; 'G'
        JNZ MON_CMD_K
        CALL MON_GO
        JMP MON_CLR_DIGIT
MON_GO:
        LHLD MON_WORD
        PCHL
MON_CMD_K:
        CPI 4BH                     ; 'K'
        JNZ MON_CMD_P
        MVI A,01H
        STA OUT_MODE
        JMP SERIAL_POLL
MON_CMD_P:
        CPI 50H                     ; 'P'
        JNZ MON_CMD_M
        MVI A,02H
        STA OUT_MODE
        JMP SERIAL_POLL
MON_CMD_M:
        CPI 4DH                     ; 'M'
        JNZ MON_CMD_O
        MVI A,0CH
        STA RX_STATE
        JMP SERIAL_POLL
MON_CMD_O:
        CPI 4FH                     ; 'O'
        JNZ MON_HEX_DIGIT
        MVI A,00H
        STA OUT_MODE
        JMP SERIAL_POLL
MON_HEX_DIGIT:
        CPI 3AH                     ; ':'
        JM MON_HEX_SHIFT
        ADI 09H
MON_HEX_SHIFT:
        ANI 0FH
        LHLD MON_WORD
        DAD H
        DAD H
        DAD H
        DAD H
        ORA L
        MOV L,A
        SHLD MON_WORD
        MVI A,00H
        STA RX_STATE
        MVI A,01H
        STA MON_DIGIT_FLAG
        JMP SERIAL_POLL
TX_STATE_N:
        CPI 03H
        JZ TX_CR                    ; state 3: send CR
        CPI 04H
        JZ TX_LF                    ; state 4: send LF
        CPI 05H
        JZ TX_PTR_HI
        CPI 06H
        JZ TX_ECHO                  ; state 6/8/B: echo char
        CPI 07H
        JZ TX_PTR_LO
        CPI 08H
        JZ TX_ECHO
        CPI 09H
        JZ TX_SPACE                 ; state 9: send space
        CPI 0AH
        JZ TX_MEM_BYTE
        CPI 0BH
        JZ TX_ECHO
        CPI 0CH
        JNZ TX_WAIT_TXRDY
        XRA A
        STA MON_WORD
        STA MON_WORD_HI
        STA RX_STATE

; TX_DASH: send '-'. The three LXI H instructions are 21H skip-prefixes over
; MVI A,' ' / MVI A,0DH / MVI A,0AH so that entries at 12D1/12D4/12D7 send those chars.
TX_DASH:
        MVI A,2DH                   ; '-'
TX_SPACE     EQU  $+1
        LXI H,203EH                 ; 21H skip prefix: MVI A,' ' at 12D1
TX_CR        EQU  $+1
        LXI H,0D3EH                 ; 21H skip prefix: MVI A,0DH at 12D4
TX_LF        EQU  $+1
        LXI H,0A3EH                 ; 21H skip prefix: MVI A,0AH at 12D7
        STA USART_DATA
        JMP SERIAL_POLL
TX_WAIT_TXRDY:
        LDA USART_CTRL
        RAR
        RAR
        JNC TX_DUMP_STATE
        XRA A
        STA RX_STATE
        JMP SERIAL_POLL
TX_DUMP_STATE:
        LDA RX_STATE
        CPI 0DH
        JZ TX_DUMP_BYTE
        CPI 0EH
        JZ TX_ECHO
        MVI A,0CH
        STA RX_STATE
        JMP TX_DASH
TX_DUMP_BYTE:
        LHLD MON_WORD
        LDA MON_LAST
        CMP M
        JZ TX_DUMP_SAME
        MOV A,M
        STA MON_LAST
        JMP TX_HEX_BYTE
TX_DUMP_SAME:
        MVI A,0CH
        STA RX_STATE
        RET
TX_ECHO:
        LDA RX_CHAR
        STA USART_DATA
        JMP SERIAL_POLL
TX_PTR_LO:
        LDA MON_PTR
        JMP TX_HEX_BYTE
TX_PTR_HI:
        LDA MON_PTR_HI
TX_HEX_BYTE:
        PUSH PSW
        RAR
        RAR
        RAR
        RAR
        ANI 0FH
        CPI 0AH
        JM TX_HEX_HI
        ADI 07H
TX_HEX_HI:
        ADI 30H                     ; '0'
        STA USART_DATA
        POP PSW
        ANI 0FH
        CPI 0AH
        JM TX_HEX_LO
        ADI 07H
TX_HEX_LO:
        ADI 30H                     ; '0'
        STA RX_CHAR
        JMP SERIAL_POLL
TX_MEM_BYTE:
        LHLD MON_PTR
        MOV A,M
        JMP TX_HEX_BYTE

; PLOT_OUT: strip-chart output mode. Emits CR, LF then 80 columns with ' ' / '!' / '"' / '#'
; marking the two values from PLOT_VALUES.
PLOT_OUT:
        LDA USART_CTRL
        RRC
        RNC
        LDA PIO1_PC
        ORA C
        STA PIO1_PC
        LDA PLOT_COL
        CPI 50H                     ; 'P'
        MVI D,0DH
        JZ PLOT_SEND
        LDA PLOT_COL
        CPI 51H                     ; 'Q'
        JNZ PLOT_COLUMN
        MVI A,00H
        STA PLOT_COL
        CALL PLOT_VALUES
        MOV H,B
        MOV L,C
        SHLD PLOT_BASE
        MVI D,0AH
        JMP PLOT_SEND
PLOT_COLUMN:
        LHLD PLOT_BASE
        MOV B,H
        MOV C,L
        MVI D,20H                   ; ' '
        LDA PLOT_COL
        CMP B
        JNZ PLOT_CHK_C
        MOV A,D
        ORI 01H
        MOV D,A
PLOT_CHK_C:
        CMP C
        JNZ PLOT_SEND
        MOV A,D
        ORI 02H
        MOV D,A
PLOT_SEND:
        LXI H,PLOT_COL
        INR M
        MOV A,D
        STA USART_DATA
        RET
PLOT_VALUES:
        LDA SEL_A
        LXI H,REC_MASTER_14
        CPI 0AH
        JNC PV_SCALE
        LXI H,SLOT_FLAGS
        ADD L
        MOV L,A
        MOV A,M
        LXI H,REC_SEC_14
PV_INDEX:
        ANI 03H
        LXI D,0019H                 ; record stride 25
        DCR A
        JM PV_SCALE
        DAD D
        JMP PV_INDEX
PV_SCALE:
        MOV A,M
        RRC
        RRC
        ADI 08H
        ANI 3FH                     ; '?'
        INR A
        INR A
        INR A
        MOV B,A
        INX H
        INX H
        INX H
        MOV A,M
        CMA
        RRC
        RRC
        ADI 08H
        ANI 3FH                     ; '?'
        INR A
        INR A
        INR A
        MOV C,A
        RET

; DISP_REFRESH: write the 8279 display RAM (cmd 90H = write, auto-inc, addr 0).
; 7 bytes: 3 pairs interleaving high nibbles of 7034..7036 with 7037..7039, then 703A.
; Never reached from the dumped halves; called from the missing half.
DISP_REFRESH:
        MVI A,90H
        STA KDC_CMD
        LXI B,M_7037
        LXI H,M_7034
        MVI E,03H
DISP_LOOP:
        MOV A,M
        ANI 0F0H
        MOV D,A
        LDAX B
        RRC
        RRC
        RRC
        RRC
        ANI 0FH
        ORA D
        STA KDC_DATA
        MOV A,M
        RLC
        RLC
        RLC
        RLC
        ANI 0F0H
        MOV D,A
        LDAX B
        ANI 0FH
        ORA D
        STA KDC_DATA
        INX H
        INX B
        DCR E
        JNZ DISP_LOOP
        LDA M_703A
        STA KDC_DATA
        RET

; READ_SWITCHES: read the 6 thumbwheel rows via the 8279 sensor RAM (cmd 50H).
; Rows 0,1 -> SEL_A/SEL_B (digit+1, must be 1..9); rows 2..5 -> GRI (first digit >= 4).
; Invalid settings call the X_199x error handlers in the missing half and retry.
READ_SWITCHES:
        MVI A,0E0H
        STA KDC_CMD                 ; 8279: end interrupt
        MVI A,50H                   ; 'P'
        STA KDC_CMD                 ; 8279: read sensor RAM row 0, auto-inc
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        INR A
        CPI 0AH
        JC RSW_SELB
        CALL X_1990
        JMP READ_SWITCHES
RSW_SELB:
        STA SEL_A
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        INR A
        CPI 0AH
        JC RSW_GRI1
        CALL X_1995
        JMP READ_SWITCHES
RSW_GRI1:
        STA SEL_B
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        JC RSW_GRI1_CHK
        CALL X_199A
        JMP READ_SWITCHES
RSW_GRI1_CHK:
        CPI 04H
        JNC RSW_GRI2                ; GRI first digit must be 4..9
        CALL X_199A
        JMP READ_SWITCHES
RSW_GRI2:
        RLC
        RLC
        RLC
        RLC
        MOV L,A
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        JC RSW_GRI3
        CALL X_199F
        JMP READ_SWITCHES
RSW_GRI3:
        ORA L
        MOV L,A
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        JC RSW_GRI4
        CALL X_19A4
        JMP READ_SWITCHES
RSW_GRI4:
        RLC
        RLC
        RLC
        RLC
        MOV H,A
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        JC RSW_STORE_GRI
        CPI 0BH
        JZ RSW_GRI4_BLANK
        CALL X_19A9
        JMP READ_SWITCHES
RSW_GRI4_BLANK:
        MVI A,00H
RSW_STORE_GRI:
        ORA H
        MOV H,A
        SHLD GRI_SW
        JMP SCAN_SWITCHES

; SW_TO_DIGIT: convert a sensor row byte to a digit. Rows are 9's-complement BCD on bits 0..5:
; digit = 9 - (row & 3FH), valid (carry set) when row & 3FH <= 9. Otherwise returns
; 0BH for the blank position (carry clear).
SW_TO_DIGIT:
        ANI 3FH                     ; '?'
        XRI 0FFH
        ADI 0AH
        CPI 0AH
        RC
        RRC
        RRC
        RRC
        RRC
        ADI 0CH
        ANI 0FH
        STC
        CMC
        RET

; TICK_TASK: run once per RST 7.5 tick. TICK_BCD += 2 (BCD); every 20 ticks call X_19E7.
; If RST 5.5 (8279 IRQ) is pending: send End-Interrupt (0E0H) and set KEY_CHANGED;
; on a later tick with KEY_CHANGED set, rescan the switches.
TICK_TASK:
        LDA TICK_BCD
        INR A
        INR A
        XRI 00H
        DAA
        STA TICK_BCD
        ANI 3FH                     ; '?'
        CZ X_19E7
        RIM
        ANI 10H
        JZ TICK_CHK_KEYS
        MVI A,0E0H
        STA KDC_CMD                 ; 8279: end interrupt (clear IRQ)
        MVI A,01H
        STA KEY_CHANGED
        RET
TICK_CHK_KEYS:
        LDA KEY_CHANGED
        CPI 00H
        RZ

; SCAN_SWITCHES: read sensor rows 0..5 and 6..7. Row 0/1 -> SEL_A/SEL_B, rows 2..5 -> SW_D1..4,
; rows 6/7 bit 7/6 -> BTN_STATE / BUTTONS (push-button edges).
; SEL_B = 0CH (blank) enters set-up: SW_D1..4 latched to SW_HI/SW_LO; SW_D1 = blank selects
; a configuration item by SW_D2: 0-3 baud (110/300/1200/19200), 4-9 OPTIONS bits.
SCAN_SWITCHES:
        MVI A,50H                   ; 'P'
        STA KDC_CMD                 ; 8279: read sensor RAM row 0, auto-inc
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        INR A
        STA SEL_A
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        INR A
        STA SEL_B
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        STA SW_D1
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        STA SW_D2
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        STA SW_D3
        LDA KDC_DATA
        CALL SW_TO_DIGIT
        STA SW_D4
        MVI A,00H
        STA KEY_CHANGED
        MVI A,56H                   ; 'V'
        STA KDC_CMD                 ; 8279: read sensor RAM row 6, auto-inc
        LDA KDC_DATA
        MOV B,A
        ANI 80H
        JZ SCAN_BTN_ROW7
        LDA BTN_STATE
        XRI 80H
        STA BTN_STATE
SCAN_BTN_ROW7:
        MOV A,B
        ANI 40H                     ; '@'
        RLC
        MOV B,A
        LDA KDC_DATA
        MOV C,A
        ANI 80H
        JZ SCAN_BTN_CLR
        LDA BTN_STATE
        ORI 40H                     ; '@'
        JMP SCAN_BTN_STORE
SCAN_BTN_CLR:
        LDA BTN_STATE
        ANI 0BFH
SCAN_BTN_STORE:
        STA BTN_STATE
        MOV A,C
        ANI 40H                     ; '@'
        ORA B
        STA BUTTONS
        LDA SEL_B
        CPI 0CH                     ; SEL_B blank -> set-up mode
        JNZ SCAN_NORMAL
        LDA BTN_STATE
        MOV B,A
        ANI 40H                     ; '@'
        STA BTN_STATE
        MOV A,B
        RLC
        JNC SCAN_BTN_EDGES
        LDA SW_LATCHED
        CPI 00H
        JNZ SCAN_CLR_STATS
        LDA SW_D1
        RLC
        RLC
        RLC
        RLC
        ANI 0F0H
        MOV B,A
        LDA SW_D2
        ANI 0FH
        ORA B
        STA SW_HI
        LDA SW_D3
        RLC
        RLC
        RLC
        RLC
        ANI 0F0H
        MOV B,A
        LDA SW_D4
        ANI 0FH
        ORA B
        STA SW_LO
        MVI A,00H
        STA VAR_704F
        MVI A,01H
        STA SW_LATCHED
        JMP SCAN_BTN_EDGES
SCAN_CLR_STATS:
        MVI A,00H
        STA VAR_70BD
        STA VAR_70BE
        STA VAR_7050
        STA VAR_7051
SCAN_BTN_EDGES:
        LDA BUTTONS
        MOV B,A
        MVI A,00H
        STA BUTTONS
        MOV A,B
        RLC
        JNC SCAN_BTN_EDGE2
        LDA STATUS_BITS
        ORI 80H
        STA STATUS_BITS
SCAN_BTN_EDGE2:
        MOV A,B
        RLC
        RLC
        JNC SCAN_DONE
        LDA STATUS_BITS
        ANI 7FH
        STA STATUS_BITS
SCAN_DONE:
        RET
SCAN_NORMAL:
        LDA BUTTONS
        CPI 00H
        RZ
        LDA SEL_B
        CPI 0BH
        RZ
        MVI A,02H
        STA RESTART_REQ
        LDA BUTTONS
        ANI 40H                     ; '@'
        RZ
        LDA SW_D1
        CPI 0BH                     ; SW_D1 blank -> configuration item
        JNZ SCAN_SEL_CHK
        LDA SW_D3
        RLC
        RLC
        RLC
        RLC
        ANI 0F0H
        MOV B,A
        LDA SW_D4
        ORA B
        STA UNIT_ID
        LDA SW_D2
        CPI 00H
        JNZ CFG_BAUD_1
        LXI H,458AH                 ; timer 058AH (1418): 110 baud
        SHLD PIO2_TMRLO
        MVI A,0C3H
        STA PIO2_CMD
        JMP SCAN_SEL_CHK
CFG_BAUD_1:
        CPI 01H
        JNZ CFG_BAUD_2
        LXI H,4208H                 ; timer 0208H (520): 300 baud
        SHLD PIO2_TMRLO
        MVI A,0C3H
        STA PIO2_CMD
        JMP SCAN_SEL_CHK
CFG_BAUD_2:
        CPI 02H
        JNZ CFG_BAUD_3
        LXI H,4082H                 ; timer 0082H (130): 1200 baud
        SHLD PIO2_TMRLO
        MVI A,0C3H
        STA PIO2_CMD
        JMP SCAN_SEL_CHK
CFG_BAUD_3:
        CPI 03H
        JNZ CFG_OPT_4
        LXI H,4008H                 ; timer 0008H (8): 19200 baud
        SHLD PIO2_TMRLO
        MVI A,0C3H
        STA PIO2_CMD
        JMP SCAN_SEL_CHK
CFG_OPT_4:
        CPI 04H
        JNZ CFG_OPT_5
        MVI A,00H
        STA OPTIONS
        JMP SCAN_SEL_CHK
CFG_OPT_5:
        CPI 05H
        JNZ CFG_OPT_6
        MVI A,81H
        STA OPTIONS
        JMP SCAN_SEL_CHK
CFG_OPT_6:
        CPI 06H
        JNZ CFG_OPT_7
        MVI A,82H
        STA OPTIONS
        JMP SCAN_SEL_CHK
CFG_OPT_7:
        CPI 07H
        JNZ CFG_OPT_8
        MVI A,84H
        STA OPTIONS
        JMP SCAN_SEL_CHK
CFG_OPT_8:
        CPI 08H
        JNZ CFG_OPT_9
        MVI A,88H
        STA OPTIONS
        JMP SCAN_SEL_CHK
CFG_OPT_9:
        CPI 09H
        JNZ SCAN_SEL_CHK
        MVI A,80H
        STA OPTIONS
SCAN_SEL_CHK:
        LDA SEL_A
        LXI H,SLOT_COUNT
        CMP M
        RP
        CALL X_1DBD
        JC SCAN_SEL_STORE
        LDA SLOT_IDX_B
        CALL GET_FLAGS_A
        ANI 0C0H
        CPI 80H
        RZ
        CALL X_1E05
SCAN_SEL_STORE:
        STA SLOT_RESULT
        MVI A,01H
        STA NEW_DATA
        RET

; TX_SERVICE: when OUT_MODE = 0 and 8251 TxRDY, send next char from PRTBUF.
TX_SERVICE:
        LDA OUT_MODE
        CPI 00H
        RNZ
        LDA USART_CTRL
        RRC
        RNC
        LDA TX_PENDING
        RRC
        RC
        LDA PIO1_PC
        ORI 01H
        STA PIO1_PC
        CALL PRTBUF_GET
        JNC TX_SEND
        MVI A,01H
        STA TX_PENDING
        RET
TX_SEND:
        STA USART_DATA
        RET

; PRTBUF_GET: pull next char from the print buffer (PRTBUF_PTR walks down to PRTBUF).
PRTBUF_GET:
        LHLD PRTBUF_PTR
        LXI D,PRTBUF
        MOV A,D
        CMP H
        JNZ PRTBUF_POP
        MOV A,E
        CMP L
        JNZ PRTBUF_POP
        MOV A,M
        STC
        RET
PRTBUF_POP:
        STC
        CMC
        DCX H
        MOV A,M
        SHLD PRTBUF_PTR
        RET

; REPORT_TASK: sequence the periodic data report over the serial port (RPT_STATE 0..8,
; 0FEH = idle, 0FFH = armed). Items are formatted by X_189B / X_1878 in the missing half.
REPORT_TASK:
        LDA RPT_STATE
        CPI 0FEH
        JNZ RPT_RUNNING
        LDA PROTO_STATE
        CPI 00H
        JZ RPT_CHK_IDLE
        CPI 02H
        RNZ
        MVI A,01H
        STA PROTO_STATE
        JMP RPT_ARM
RPT_CHK_IDLE:
        LDA TICK_BCD
        CPI 00H
        RNZ
        LDA OPTIONS
        RLC
        JNC RPT_ARM
        LDA VAR_704F
        ANI 0FH
        CPI 00H
        RNZ
        LDA OPTIONS
        RRC
        JC RPT_ARM
        LDA VAR_704F
        CPI 00H
        RNZ
        LDA OPTIONS
        RRC
        RRC
        JC RPT_ARM
        LDA SW_LO
        ANI 0FH
        CPI 00H
        RNZ
        LDA OPTIONS
        RRC
        RRC
        RRC
        JC RPT_ARM
        LDA SW_LO
        CPI 00H
        RNZ
        LDA OPTIONS
        RRC
        RRC
        RRC
        RRC
        JC RPT_ARM
        LDA SW_HI
        CPI 00H
        RNZ
RPT_ARM:
        MVI A,0FFH
        STA RPT_STATE
        RET
RPT_RUNNING:
        LDA RPT_STATE
        CPI 09H
        JZ RPT_FINISH
        LDA TX_PENDING
        CPI 00H
        RZ
        MVI A,00H
        STA TX_PENDING
        LDA RPT_STATE
        INR A
        STA RPT_STATE
        CPI 09H
        JZ X_1940
        JMP RPT_NEXT_ITEM
RPT_FINISH:
        MVI A,0FEH
        STA RPT_STATE
        RET
RPT_NEXT_ITEM:
        LDA RPT_STATE
        CPI 00H
        JNZ RPT_ITEM_N
        LDA SLOT_FLAGS
        ANI 50H                     ; 'P'
        CPI 50H                     ; 'P'
        RNZ
        LDA SLOT_FLAGS
        JMP RPT_FORMAT
RPT_ITEM_N:
        MOV C,A
        MVI B,00H
        LXI H,SLOT_FLAGS
        DAD B
        MOV A,M
        ANI 0D0H
        CPI 0D0H
        MOV A,M
        RNZ
RPT_FORMAT:
        LDA RPT_STATE
        LXI H,SLOTREC_3
        CALL MUL9_INDEX             ; HL = SLOTREC_3 + 9 * item
        CALL X_189B
        CALL X_1878
        LDA RPT_STATE
        CPI 00H
        JNZ RPT_ITEM_OFS
        LXI H,GRI_BCD_HI
        JMP X_1804
RPT_ITEM_OFS:
        LXI H,0FF56H                ; operand high byte is at 1800 in the undumped half: real value unknown (dump shows 0FFH)
; ---- 1801-1FFF: unprogrammed / not dumped (reads as 0FFH) ----
