#!/usr/bin/env node
'use strict';
/*
 * addr-decode.js -- the device-address decoder, shared between the
 * emulator (tools/emu8085.js) and the CUPL generator below, so both are
 * built from one table and can't drift apart.
 *
 * Mirrors the 8205 (U45) 3-to-8 decoder's Y0-Y7 mapping as reconstructed in
 * docs/hardware.md's "Address decoding" table: decode is on A14..A12 only.
 * A15 (IO/M) is deliberately NOT a decoder input here, matching the board:
 * hardware.md's own reconstruction has A15 wired directly into each 8155's
 * own IO/M pin, not through U45 -- so PIO1/PIO2's chip-select below covers
 * BOTH that 8155's RAM window and its register window; the 8155 itself
 * (tools/emu8085.js's Intel8155.read8/write8) is what tells them apart.
 *
 * This module also models that decode logic as though it were built from a
 * PAL16R8 or PAL20R10 instead of the board's actual discrete TTL logic
 * (8205 + glue, confirmed on the physical board -- see hardware.md), and
 * can emit matching CUPL (.PLD) source for either device. That's an
 * emulator/design-tool choice -- a documented hypothetical replacement for
 * the TTL glue, not a claim about what's actually on the board. See
 * docs/pal-decoder.md.
 *
 * Usage: node tools/addr-decode.js           writes pal/addr_decoder_16r8.pld
 *                                             and pal/addr_decoder_20r10.pld
 */
const fs = require('fs');
const path = require('path');

const CS = {
  ROM1: 'CS_ROM1', ROM2: 'CS_ROM2', EXPROM: 'CS_EXPROM', UNUSED: 'CS_UNUSED',
  USART: 'CS_USART', KDC: 'CS_KDC', PIO1: 'CS_PIO1', PIO2: 'CS_PIO2',
};

// One product term per output: a pure 3-to-8 decode, one minterm per Y line,
// matching the 8205's Y0-Y7 order exactly (see hardware.md's decode table).
const ADDR_DECODE_TERMS = [
  { name: CS.ROM1, pins: ['!A14', '!A13', '!A12'] }, // Y0, sel 000: ROM1 0000-0FFF
  { name: CS.ROM2, pins: ['!A14', '!A13', 'A12'] }, // Y1, sel 001: ROM2 1000-1FFF
  { name: CS.EXPROM, pins: ['!A14', 'A13', '!A12'] }, // Y2, sel 010: expansion ROM 2000-2FFF
  { name: CS.UNUSED, pins: ['!A14', 'A13', 'A12'] }, // Y3, sel 011: unused
  { name: CS.USART, pins: ['A14', '!A13', '!A12'] }, // Y4, sel 100: 8251A
  { name: CS.KDC, pins: ['A14', '!A13', 'A12'] }, // Y5, sel 101: 8279
  { name: CS.PIO1, pins: ['A14', 'A13', '!A12'] }, // Y6, sel 110: 8155 #1
  { name: CS.PIO2, pins: ['A14', 'A13', 'A12'] }, // Y7, sel 111: 8155 #2
];

// Pin assignments are this project's own choice (there's no real target
// socket to match) -- ascending order, CLK/inputs first, then OE, then the
// registered outputs in Y0-Y7 order. Anyone burning this into a real chip
// to physically replace U45 should renumber to match their own wiring.
const DEVICE_SPECS = {
  '16R8': {
    device: 'p16r8',
    partno: 'ADDRDEC16R8',
    pins: {
      clk: 1,
      inputs: { A12: 2, A13: 3, A14: 4 },
      oe: 11,
      outputs: {
        CS_ROM1: 12, CS_ROM2: 13, CS_EXPROM: 14, CS_UNUSED: 15,
        CS_USART: 16, CS_KDC: 17, CS_PIO1: 18, CS_PIO2: 19,
      },
    },
    note: '20-pin PAL16R8: 8 registered outputs, an exact fit for the 8205\'s 8 Y-outputs. No spare outputs.',
  },
  '20R10': {
    device: 'p20r10',
    partno: 'ADDRDEC20R10',
    pins: {
      clk: 1,
      inputs: { A12: 2, A13: 3, A14: 4 },
      oe: 13,
      outputs: {
        CS_ROM1: 14, CS_ROM2: 15, CS_EXPROM: 16, CS_UNUSED: 17,
        CS_USART: 18, CS_KDC: 19, CS_PIO1: 20, CS_PIO2: 21,
      },
    },
    note: '24-pin PAL20R10: 10 registered outputs, 8 used here; pins 22-23 are spare (e.g. for a resolved U39/8212 select, or a second expansion-ROM socket) and left undeclared.',
  },
};

function generateCupl(deviceKey, opts = {}) {
  const spec = DEVICE_SPECS[deviceKey];
  if (!spec) throw new Error(`unknown PAL device ${deviceKey}, expected one of ${Object.keys(DEVICE_SPECS).join(', ')}`);
  const { designer = 'Matthew Whited', company = '', date = new Date().toISOString().slice(0, 10) } = opts;
  const p = spec.pins;
  const lines = [];
  lines.push(`Name     ${spec.partno};`);
  lines.push(`PartNo   00;`);
  lines.push(`Date     ${date};`);
  lines.push(`Revision 01;`);
  lines.push(`Designer ${designer};`);
  lines.push(`Company  ${company};`);
  lines.push(`Assembly None;`);
  lines.push(`Location ;`);
  lines.push(`Device   ${spec.device};`);
  lines.push('');
  lines.push('/* Auto-generated by tools/addr-decode.js -- do not hand-edit, regenerate instead.');
  lines.push(' *');
  lines.push(' * Emulated PAL replacement for the board\'s device-mapping logic (U45 8205 +');
  lines.push(' * TTL glue, per docs/hardware.md); NOT verified against the physical board --');
  lines.push(' * see docs/pal-decoder.md. Decodes A[14:12] into 8 active-low chip-select');
  lines.push(' * lines matching the 8205\'s Y0-Y7 mapping one-for-one.');
  lines.push(' *');
  lines.push(' * A15 (IO/M) is intentionally NOT decoded here: on the reconstructed board it');
  lines.push(' * goes directly to each 8155\'s own IO/M pin, bypassing the decoder entirely,');
  lines.push(' * so CS_PIO1/CS_PIO2 below each cover that 8155\'s RAM window AND its register');
  lines.push(' * window -- the 8155 itself tells them apart, not this chip.');
  lines.push(` *\n * ${spec.note}`);
  lines.push(' */');
  lines.push('');
  lines.push(`PIN ${p.clk} = CLK;`);
  for (const [name, num] of Object.entries(p.inputs)) lines.push(`PIN ${num} = ${name};`);
  lines.push(`PIN ${p.oe} = OE;`);
  for (const [name, num] of Object.entries(p.outputs)) lines.push(`PIN ${num} = !${name}; /* active low, like the 8205's Y outputs */`);
  lines.push('');
  for (const t of ADDR_DECODE_TERMS) {
    lines.push(`${t.name} = ${t.pins.join(' & ')};`);
  }
  lines.push('');
  return lines.join('\n');
}

function main() {
  const base = path.resolve(__dirname, '..');
  const outDir = path.join(base, 'pal');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  for (const key of Object.keys(DEVICE_SPECS)) {
    const text = generateCupl(key);
    const outPath = path.join(outDir, `addr_decoder_${key.toLowerCase()}.pld`);
    fs.writeFileSync(outPath, text);
    console.error(`addr-decode: wrote ${outPath}`);
  }
}

module.exports = { CS, ADDR_DECODE_TERMS, DEVICE_SPECS, generateCupl };

if (require.main === module) main();
